### ISSUE TITLE
Docker exec not writing to stream

### ISSUE THREAD

**Issue by BenHall** [apocas/dockerode#184] opened 2015-11-03 15:31 UTC
Hello,

I'm trying to use Docker Exec in order to attach to a container and execute commands. 

I change the stdin and use the same approach as when using container and attach but it doesn't seem to have the same response. I get the response the cmd (bash prompt) but when I try and write a command into bash it fails. 

Here is an example:

https://gist.github.com/BenHall/0863b723fde31f712301

Any ideas?

Ben

**Comment by rmg** [comment] 2015-11-03 17:28
@BenHall It _shouldn't_ be required, but I've found adding a 100ms or so delay before writing to the exec stream makes a huge difference. I haven't yet had time to figure out the root cause, but I'd be curious to hear if it helps with your case or not.

**Comment by BenHall** [comment] 2015-11-04 09:42
@rmg Great idea, but sadly that doesn't seem to work for me :(

**Comment by gugu** [comment] 2016-04-17 18:08
@BenHall maybe because you have typo in "Detach" argument? It is written as "Detact"

**Comment by apocas** [comment] 2016-06-01 09:02
Can we close this one?

**Comment by BenHall** [comment] 2016-06-01 09:50
Yes. With the right combination of settings it does work as expected

**Closed** 2016-06-01 09:49 UTC
Labels: needs inspection

**Comment by harshaa947** [comment] 2016-06-05 18:29
Can you share your working code .. it doesn't seem to work for me

**Comment by tces1** [comment] 2017-08-30 06:17
I have found a problem in the docs of docker API, the exec start request body just '' Detach 'and "Tty", i have the problem, Imcompelete, only when the configuration file with stream: true, stdin: true, stdout: true, stderr: true, chunk can write correctly. Do not know why, -_- !!!
