### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Clashsoft** [apocas/dockerode#749] opened 2023-10-31 13:14 UTC
The v4 Release page does not provide any info. What changed and why is it a breaking change? Can you please provide a changelog?

**Comment by Clovel** [comment] 2023-11-06 09:16
I would also be interrested in knowing what changed and if there are any breaking changes.

**Comment by Clovel** [comment] 2023-11-06 09:20
It also seems that docker-modem has the same issue. 

And both `@types/` packages are stuck at v3.X.Y

**Comment by nwalters512** [comment] 2023-11-06 20:34
Duplicate of #746?

In the interest of crowd-sourcing a changelog, here's a breaking change I found in v4: https://github.com/apocas/dockerode/issues/751

**Comment by apocas** [comment] 2023-12-23 00:53
It was the only one. And it was wrongly introduced, it was reverted since then.

**Closed by apocas** 2023-12-23 00:53 UTC
