### ISSUE TITLE
How about promisfying the APIs?

### ISSUE THREAD

**Issue by knight42** [apocas/dockerode#300] opened 2016-09-25 17:49 UTC

**Comment by Seikho** [comment] 2016-09-26 08:02
Duplicate of #171 
As recommended in #171, https://www.npmjs.com/package/dockerode-promise

**Comment by knight42** [comment] 2016-09-26 09:51
Got it. I think this can be noted somewhere. Thanks anyway!

**Comment by apocas** [comment] 2017-03-03 10:22
Just pushed to the repo a promise based interface, check it out :)

**Comment by knight42** [comment] 2017-03-03 10:58
@apocas Great work! Thank you!

Em... In some cases, I prefer another promise library instead of the native one, e.g. bluebird. Could you enable users to plug in their favourite promise library?

I think that can be achieved like this:

Users pass their promise library to Docker:
```js
const docker = new Docker({
  socketPath: '...',
  Promise: require('bluebird')
})
```

then the constructer can save it in the `Modem` instance

```js
Docker() {
...
  this.modem.Promise = opts.Promise || global.Promise
...
}
```

After that, just replace `return new Promise()` with `return new this.modem.Promise()`.

**Comment by apocas** [comment] 2017-03-03 11:00
Humm, interesting :)

Yes this is a good idea.

**Comment by apocas** [comment] 2017-03-05 13:03
Done :)
Thanks for the feedback!

**Closed** 2017-03-05 13:04 UTC
Labels: enhancement

**Comment by knight42** [comment] 2017-03-05 16:35
@apocas Great! I can't wait for its publication to NPM!
